employeePortal/urls.py
from django.contrib import admin
from django.urls import path,include
from myApp import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('myApp/',include('myApp.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myApp/urls.py
from django.urls import path
from myApp import views

app_name = 'myApp'

urlpatterns = [
    path('login/',views.uslogin,name='login'),
    path('home/',views.home,name='home'),
    path('index/',views.index,name='index'),
    path('leave/',views.leaveView,name='leave'),
    path('contact/',views.contact,name='contact'),
    path('health/',views.health,name='health'),
    path('holiday/',views.holidays,name='holidays'),
    path('job/',views.job,name='job'),
    path('salary/',views.salary,name='salary'), 
    path('submission/',views.submission,name='submission'), 
    path('directory/',views.directory,name='directory'), 
    path('family/',views.family,name='family'), 
    path('check_user',views.check_user,name='check_user'), 
    path('uslogout/',views.uslogout,name='logout'),
    path('personal_info/',views.personal_info,name='personal_info'),
    path('health_record/',views.health_info,name='health_record'),
    path('family_record/',views.family_info,name='family_record'),
    path('change_password',views.change_password,name='change_password'),
    path('input_salary',views.input_salary,name='inputsalary'),
    path('input_job',views.input_job,name='input_job'),
    path('change_profile',views.change_profile,name='change_profile'),
    path('user_profile',views.profile,name='user_profile'),
    path('hrdash',views.hr_dash,name='hrdash'),
    path('SignUpApprove',views.SignUp_Approve,name='SignUpApprove'),   
    path('documentReview',views.document_review,name='documentReview'),    
    path('leave_approval',views.leave_approval,name='leaveapproval'),    
    path('send_mail',views.send_mail,name='mail'),    
    path('documentAppprove',views.document_approval,name='documentApprove'),    
    path('hr_password',views.hr_password,name='hrpassword'),    
    path('announce',views.announcements,name='announce'),    
    path('leaveDetails',views.leaveDetails,name='leavedet'),    
    path('docDetails',views.doc_Details,name='docDetails'),    
    path('leave_assign',views.leave_assign,name='leaveassign'),     
    path('forgot_password',views.forgot_password,name='forgotpassword'),    
    path('holidayupdate',views.holiday_update,name='holidayupdate'),   
    path('addattendance',views.addattendance,name='addatt'),    
    path('hrsend_mail',views.hrsend_mail,name='hr_mail'),    
    path('event',views.events,name='event'),    
    path('changestatus',views.changestatus,name="changestatus"),
    path('attendanceUser',views.attendanceUser,name="attendanceUser"),
    path('HRprofile',views.HRprofile,name="HR_profile"),
    path('HRchange_profile',views.HRchange_profile,name="hrchangeprofile"),
  
]

templates/SignupApproval.html
{% extends 'hr.html'%}
{% load staticfiles %}
{% block head %}
{% endblock %}
{% block mycode %}
<div class="container">
  <div class="row">
    <div class="col-md-8" style="margin-left:10%;margin-right:20%;">
      <table class="table table-striped">
        <thead style="background:#D2691E">
          <tr>
            <th>Name</th>
            <th>Username</th>
            <th>Action</th>
            
          </tr>
        </thead>
        <tbody style="background:cornsilk">
          {% for i in all %}
          <tr>
              <td>{{i.user.first_name}} {{i.user.last_name}}</td>
              <td>{{i.user.id}} {{i.user.username}}</td>
              <td>
                {% if i.user.is_active %}
                <a href="{% url 'myApp:SignUpApprove' %}?id={{i.user.id}}&action=app" class="btn btn-warning">Deactivate</a>
                {% else %}
                <a href="{% url 'myApp:SignUpApprove' %}?id={{i.user.id}}&action=app" class="btn btn-success">Approve</a>
                {% endif %}
                <a href="{% url 'myApp:SignUpApprove' %}?id={{i.id}}&action=delete" class="btn btn-danger">Delete</a>
                
              </td>
          </tr>
          {% endfor %}
         </tbody>
      </table>
    </div>
  </div>

</div>
          
                   
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>         
      <script src="{% static 'animate/js/animate.js' %}"></script> 

{% endblock %}

templates/documentApproval.html
{% extends 'hr.html'%}
{% load staticfiles %}
{% block head %}
{% endblock %}
{% block mycode %}
{% if status %}
<script>
    alert('{{status}}');
    window.location='/myApp/documentApprove'
</script>
{% endif %}
<div class="container">
    <div class="row">
        <div class="col-md-8" style="background: #D2691E;margin-top:20px;margin-left:15%;margin-right:15%;box-shadow:0px 0px 10px black;">
        <span class="text-light" style="margin:10px;font-size: 20px;">Document Approve Form Information :</span>
            
           
         <div style="background:cornsilk;">
                <table border="1" style="height:50px;width:100%;margin-top:20px;margin-bottom:20px;">
                       <thead>
                            <tr>
                                    <th>Name</th>
                                    <th>Reference</th>
                                    <th>Document</th>
                                    <th>Date</th>

                                    <th>Status</th>
                                    <th>Action</th>
                                </tr>
                       </thead>
                       <tbody>
                            {% for i in all %}
                        <tr>
                                <td>{{i.doc.user.first_name}}{{i.doc.user.last_name}}</td>
                                <td>{{i.reference}}</td>
                                <td><a href="/media/{{i.document}}" download><i class="fas fa-eye"></i></a></td>
                                <td>{{i.submission_date}}</td>
                                <td>{{i.status}}</td>
                                <td><form action="" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="docid"  value="{{i.id}}">
                                    <input type="submit" name="app" value="Approve" class="btn btn-success">
                                    <input type="submit" name="rej" value="Reject" class="btn btn-danger">
                                </form></td>
                        </tr>
                        {% endfor %}
                       </tbody>
                    </table>
         </div>

        </div>

    </div>

    <!-- ************AJAX************* -->
    <script>
            function getdata(id){
                $.ajax({
                    url:'{% url "myApp:docDetails"%}',
                    data:{id:id},
                    type:'get',
                    success:function(data){
                        $('#doc').val(data.document);
                        $('#ref').val(data.reference);
                        $('#desc').val(data.description);
                        $('#subdate').val(data.submission_date);
                    }
                })
            }
            </script>


    <!--*****************Modal Start*****************8-->

    <div class="modal fade" id="submit">
        <!--centered modal-->
        
        <div class="modal-dialog modal-lg">
                <!--bg white and border radious-->
<div class="modal-content" >
                
    <div class="modal-body">
         <form action="" method="POST" enctype="multipart/form-data">
             {% csrf_token %}
             <input type="hidden" name="docid" id="did">
                <div class="row">
                        <div class="col-md-12" style="background:#D2691E;">
                                <span class="text-light">Document submission</span>  
                                <span class="text-light font-weight-bold close" data-dismiss="modal" style="font-size:'30px';">&times</span>
                        </div>
                        
                            </div>
            <div class="row" style="border: 5px solid #D2691E;background: cornsilk;">
                
                <div class="col-md-6" style="margin-top:15px;">
                    <h4 style="color:#D2691E"><b>Employee Use</b></h4>
                    <hr style="color:black;">
                            
                            <div class="form-group">
                                    Document<sup class="text-danger" style="font-size:20px;">*</sup><input type="file"class="form-control clickattach" name="document" id="doc" disabled>
                                </div>
    
    
                        <script>
                            $(function(){
                                $('.attach').click(function(){
                                    $('.clickattach').click()
                                });
                            });
    
                        </script>
                        
                            <div class="form-group">
                                    References <input type="text" class="form-control" name="reference" id="ref" disabled>
                                </div>
                            <div class="form-group">
                                <div>Description</div>
                                    <textarea rows="3" cols="35" class="form-control" name="description" id="desc" placeholder="Enter text..." disabled></textarea>
                            </div>
                    </div>
                <div class="col-md-6 " style="border-left:2px solid #D2691E;margin-top:15px;">
                    <h4 style="color:#D2691E"><b>Admin Use</b></h4><hr>
                            <div class="form-group">
                                    submission date
                                    <input type="text"  class="form-control" id="subdate" name="date" disabled>

                            </div>
        
        <script>
       
        $(function(){
            let d = new Date();
            let dd = d.getDate()+'-'+parseInt(d.getMonth()+1)+'-'+d.getFullYear();
            $('#sdate').val(dd);
            
        });
        </script>
    
                            <div class="form-group">
                                    status
                                    <select name="status" id="" class="form-control">
                                        <option value="Approved">Approve</option>
                                        <option value="Rejected">Reject</option>
                                    </select>
                            </div>
                                        
                </div>
                <div class="form-group">
                    <input type="submit" class="btn btn-info" value="Ok" style="display:inline-block;margin:20px;float:right;">
                </div>
                <div class="form-group" >
                    <input type="button" class="btn btn-info close" data-dismiss="modal" value="Cancel" style="display:inline-block;margin:20px;float:right">
                </div>
            </div>   
         </form>                                 
</div>  

</div>  
        
</div>
</div>
</div>
{% endblock %}

templates/documentReview.html
{% extends 'index.html'%}
{% load staticfiles %}
{% block head %}
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <script src="{% static 'jqueryFile.js'%}"></script>
    <style>
    .modal-body{
        padding:0px !important;
    }
    tr,td{
        width:25%;
    }
   
    
    </style>
{% endblock %}
{% block mycode %}
{%if status %}
<script>
    alert('{{status}}');
</script>
{% endif %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 px-0">

                <div class="" style="height:40px;width:100%;background:#D2691E;">
                        <label class="text-light" style="margin-top:10px;padding-left:5px;">Document Review</label>
                </div>
            </div>
        </div>


<!-- ####### Tool tips ###########-->
<script>
        $(document).ready(function(){
          $('[data-toggle="tooltip"]').tooltip(); 
        });
</script>

<div class="row">
    <div class="col-md-12">
    <table border="1">
            <tr>
                    <th>Date</th>
                    <th>Document</th>
                    <th>References</th>
                    <th>Description</th>
                    <th>status</th>
        
            </tr>
            {% for i in all_docs %}
            <tr>
                <td>{{i.submission_date}}</td>
               
                    <td>
                            <a href="/media/{{i.document}}" target="_blank"><i class="fas fa-eye" style="font-size:20px;"></i> </a>
                    </td>
               
                <td>{{i.reference}}</td>
                <td>{{i.description}}</td>
                <td>
                     <button class="btn m-2"  id="st-{{i.id}}">{{i.status}}</button>
                    <script>
                    $(function(){
                        s =$('#st-{{i.id}}').html();
                        if(s=="False"){
                            $('#st-{{i.id}}').html("Pending").addClass('btn-warning btn-block');
                        }else if(s=="Approve"){
                            $('#st-{{i.id}}').removeClass('btn-warning').removeClass('btn-danger').addClass('btn-success btn-block');
                        }else{
                            $('#st-{{i.id}}').removeClass('btn-warning').removeClass('btn-success').addClass('btn-danger btn-block');
                        } 
                    });
                    </script>
                </td>
            </tr>
            {% endfor %}

    
    </table>
    </div>

</div>

</div>
{% endblock %}

templates/eventUpdates.html
{% extends "hr.html" %}
{% load staticfiles %}
{% block mycode %}
 <div class="container">
      <div class="row">
          <div class="col-md-6" style="height:30px;background:#D2691E;margin-left: 20%;margin-right:20%;box-shadow:0px 0px 10px black;color:white;">
               <h5>New Events</h5>
          </div>
      </div>
     <div class="row">
          <div class="col-md-6" style=" background: cornsilk;margin-left: 20%;margin-right:20%;box-shadow:0px 0px 10px black;">
                    {% if status %}
                    {{status}}
               {% endif %}   
               <form action="" method="POST">
                       {% csrf_token %}
                       
                      <div class="form-group">
                           <textarea name="event_text" id="text" cols="84" rows="8" style=" background: cornsilk;" class="form-control" placeholder="Write here...."></textarea>
                      </div>
                      <div class="form-group">
                           <input type="submit" class="btn btn-danger" name="Add" value="Send" style="float:right;margin-bottom:5%;">
                      </div>
                   </form>
              </div>
    </div>
 </div>
{% endblock %}

templates/family_record.html
<!DOCTYPE html>
{% load bootstrap4 %}
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                    <form method="post">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            <input type="submit">
                        </form>
            </div>
        </div>
    </div>
</body>
</html>

templates/hr.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="UTF-8">
    <title>AdminLTE 2 | Dashboard</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css'%}" rel="stylesheet" type="text/css" />    
    <!-- FontAwesome 4.3.0 -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons 2.0.0 -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />    
    <!-- Theme style -->
    <link href="{% static 'dist/css/AdminLTE.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins 
         folder instead of downloading all of them to reduce the load. -->
    <link href="{% static 'dist/css/skins/_all-skins.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="{% static 'plugins/iCheck/flat/blue.css' %}" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="{% static 'plugins/morris/morris.css' %}" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.css' %}" rel="stylesheet" type="text/css" />
    <!-- Date Picker -->
    <link href="{% static 'plugins/datepicker/datepicker3.css' %}" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="{% static 'plugins/daterangepicker/daterangepicker-bs3.css' %}" rel="stylesheet" type="text/css" />
    <!-- bootstrap wysihtml5 - text editor -->
    <link href="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css' %}" rel="stylesheet" type="text/css" />

    <style>
    .bg{
      background:rgba(0,0,0,0.5);
    }
    .text{
      color:white;
    }
    #calendar{
      color:white !important;
    }
    @media screen and (max-width:770px){
        .space{
          margin-top:0px !important;
          text-align:left !important;
        }
      }
    </style>
  </head>
  <body class="skin-blue">
    <div class="wrapper">
      
      <header class="main-header">
        <!-- Logo -->
       <p class="logo space" style="background:#D2691E;position:fixed"><b>HR&nbsp</b>Portal</p>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-fixed-top" style="background: #D2691E" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button" style="background:#D2691E">
            <span class="sr-only" >Toggle navigation</span>
          </a>
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!--  -->
                
            
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="user-image" alt="User Image"/>
                  <span class="hidden-xs">{{user.first_name}} {{user.last_name}}</span>
                </a>
                <ul class="dropdown-menu" >
                  <!-- User image -->
                  <li class="user-header" style="background: rgb(230, 126, 51)" >
                    <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image" />
                    <p>
                      {{user.first_name}} {{user.last_name}}
                      <small>Member Since {{user.date_joined}}</small>
                    </p>
                  </li>
                  <!-- Menu Body -->
                  <!-- Menu Footer-->
                  <li class="user-footer" style="background: rgb(230, 121, 43)" >
                    <div class="pull-left">
                      <a href="{% url 'myApp:logout'%}" class="btn btn-success">Sign Out</a>
                    </div>
                    <div class="pull-right">
                      <a href="{% url 'myApp:hrpassword' %}" class="btn btn-success ">Change Password</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <!-- Left side column. contains the logo and sidebar -->
      <aside class="main-sidebar" style="position:fixed">
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="{% static 'dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
              <p>{{user.first_name}} {{user.last_name}}</p>
            </div>
          </div>
          <!-- search form -->
         
          <!-- sidebar menu: : style can be found in sidebar.less -->
          <ul class="sidebar-menu" >
            <li class="active treeview">
              <a href="{% url 'myApp:hrdash' %}">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span> 
              </a>
            </li>
            <li class="treeview">
              <a href="{% url 'myApp:SignUpApprove' %}">
                <i class="fa fa-dashboard"></i> <span>SignUp approval</span> 
              </a>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-laptop"></i>
                <span>Leave</span>{{totalnot}}
                <i class="fa fa-angle-left pull-right">

                </i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{% url 'myApp:leaveassign' %}"><i class="fa fa-circle-o"></i>Leave Assign</a></li>
                <li><a href="{% url 'myApp:leaveapproval' %}"><i class="fa fa-circle-o"></i>Leave Approval</a></li>
              </ul>
            </li>
            <li class="treeview">
              <a href="{% url 'myApp:documentApprove' %}">
                <i class="fa fa-laptop"></i>
                <span>Documents</span>
              </a>
            </li>
            <li class="treeview">
              <a href="#">
                <i class="fa fa-edit"></i> <span>Attendance</span>
              </a>
            </li>
            <li class="treeview">
              <a href="{% url 'myApp:holidayupdate' %}">
                <i class="fa fa-table"></i> <span>Holidays Updates</span>
              </a>
            </li>
            <!-- <li class="treeview">
              <a href="{% url 'myApp:announce' %}">
                <i class="fa fa-edit"></i> <span>Announcements</span>
              </a>
            </li> -->
            <li class="treeview">
              <a href="#">
                <i class="fa fa-edit"></i>
                <span>Announcements</span>
                <i class="fa fa-angle-left pull-right">

                </i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{% url 'myApp:announce' %}"><i class="fa fa-circle-o"></i>Notice Update</a></li>
                <li><a href="{% url 'myApp:event' %}"><i class="fa fa-circle-o"></i>Upcoming Events</a></li>
              </ul>
            </li>
            <li class="treeview">
                <a href="#">
                  <i class="fa fa-dashboard"></i> <span>Profile</span> <i class="fa fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
      
                  <li><a href="{% url 'myApp:HR_profile' %}"><i class="fa fa-circle-o"></i>HR profile</a></li>
                  <li><a href="{% url 'myApp:hrchangeprofile' %}"><i class="fa fa-circle-o"></i>Change Profile</a></li>
                </ul>
              </li>
            <li>
              <a href="">
                <i class="fa fa-calendar"></i> <span>Calendar</span>
              </a>
            </li>
            <li>
              <a href="{% url 'myApp:hr_mail' %}">
                <i class="fa fa-envelope"></i> <span>Send Mail</span>
                <!-- <small class="label pull-right bg-yellow">12</small> -->
              </a>
            </li>
          </ul>
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Right side column. Contains the navbar and content of the page -->
      <div class="content-wrapper" id='all-content' style="background-image:url('images/body-bg.jpg');background-size:cover;">
        <!-- Content Header (Page header) -->
        <section class="content-header space" style="margin-top:35px;">
          <h1 class="text">
            Secours.we
          </h1>
          <ol class="breadcrumb">
            <li><a href="{% url 'myApp:home' %}"><i class="fa fa-dashboard text"></i> <span class="text">Home</span></a></li>
          </ol>
        </section>
        {% block mycode %}
        {% endblock %}
        <!-- Main content -->
        
      </div><!-- /.content-wrapper -->
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 2.0
        </div>
        <strong>Copyright &copy; 2019 <a href="http://almsaeedstudio.com">ACET Studio</a>.</strong> All rights reserved.
      </footer>
    </div><!-- ./wrapper -->

    <script>
    
    </script>
   <!-- jQuery 2.1.3 -->
   <script src="{% static 'plugins/jQuery/jQuery-2.1.3.min.js' %}"></script>
   <!-- jQuery UI 1.11.2 -->
   <script src="http://code.jquery.com/ui/1.11.2/jquery-ui.min.js" type="text/javascript"></script>
   <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
   <script>
     $.widget.bridge('uibutton', $.ui.button);
   </script>
   <!-- Bootstrap 3.3.2 JS -->
   <script src="{% static 'bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>    
   <!-- Morris.js charts -->
   <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
   <script src="{% static 'plugins/morris/morris.min.js' %}" type="text/javascript"></script>
   <!-- Sparkline -->
   <script src="{% static 'plugins/sparkline/jquery.sparkline.min.js' %}" type="text/javascript"></script>
   <!-- jvectormap -->
   <script src="{% static 'plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}" type="text/javascript"></script>
   <script src="{% static 'plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}" type="text/javascript"></script>
   <!-- jQuery Knob Chart -->
   <script src="{% static 'plugins/knob/jquery.knob.js' %}" type="text/javascript"></script>
   <!-- daterangepicker -->
   <script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}" type="text/javascript"></script>
   <!-- datepicker -->
   <script src="{% static 'plugins/datepicker/bootstrap-datepicker.js' %}" type="text/javascript"></script>
   <!-- Bootstrap WYSIHTML5 -->
   <script src="{% static 'plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}" type="text/javascript"></script>
   <!-- iCheck -->
   <script src="{% static 'plugins/iCheck/icheck.min.js' %}" type="text/javascript"></script>
   <!-- Slimscroll -->
   <script src="{% static 'plugins/slimScroll/jquery.slimscroll.min.js' %}" type="text/javascript"></script>
   <!-- FastClick -->
   <script src="{% static 'plugins/fastclick/fastclick.min.js' %}"></script>
   <!-- AdminLTE App -->
   <script src="{% static 'dist/js/app.min.js' %}" type="text/javascript"></script>

   <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
   <script src="{% static 'dist/js/pages/dashboard.js' %}" type="text/javascript"></script>

   <!-- AdminLTE for demo purposes -->
   <script src="{% static 'dist/js/demo.js' %}" type="text/javascript"></script>
  </body>
</html>

templates/hr_changeProfile.html
{% extends "hr.html" %}
{% load staticfiles %}
{% block mycode %}
<div class="row">
    <div class="col-md-12 px-0 py-0" >
        <h1 class=" text-center"style="color:white;">User Profile</h1>
    
    <div class="col-md-6" style="background:rgba(0,0,0,0.5);padding:20px;margin-left:25%;margin-top:2%;margin-right:20%;">
        {% if status %}
            <p class="alert alert-{{c}}">{{status}}</p>
        {% endif %}
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <div class="row">
                    <div class="col-md-6">
                        <label for="" style="color:white;">First Name</label>
                        <input type="text" class="form-control" name="first" value="{{user.first_name}}">
                    </div>
                    <div class="col-md-6">
                        <label for="" style="color:white;">Last Name</label>
                        <input type="text" class="form-control" name="last" value="{{user.last_name}}">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for style="color:white;">Username</label>
                <input type="text" class="form-control" name="username" disabled value="{{user.username}}">
            </div>
            <div class="form-group">
                <label for="" style="color:white;">Email</label>
                <input type="email" class="form-control" name="email" value="{{user.email}}">
            </div>
            <div class="form-group">
                <label for="" style="color:white;">Phone no.</label>
                <input type="number" class="form-control" name="phone" value="{{HR.contact}}" required>
            </div>
            <div class="form-group">
                
                <input type="submit" class="btn btn-primary" value="Save Changes">
            </div>
        </form>
    </div>
</div>
</div>
{% endblock %}

templates/hr_profile.html
{% extends "hr.html" %}
{% load staticfiles %}
{% block mycode %}
<style>

</style>
<div class="row">
    <div class="col-md-12"style="background-image:url('{% static 'image/3.jpg'}')">
        <h1 style="text-align: center;">User profile</h1>
        <table class="table  table-hover bg-info" style="margin-left:25%;margin-right:20%;margin-top:2%;width:50%;">
           
            <tr>
                <th>First name</th>
                <th>{{data.first_name}}</th>
            </tr>
            <tr>
                <th>Last name</th>
                <th>{{data.last_name}}</th>
            </tr>
            <tr>
                <th>username</th>
                <th>{{data.username}}</th>
            </tr>
            <tr>
                <th>Email</th>
                <th>{{data.email}}</th>
            </tr>
            <tr>
                    <th>Phone</th>
                    <th>{{data.contact}}</th>
                </tr>
            <tr>
                <th>Since username</th>
                <th>{{data.date_joined}}</th>
            </tr>
            <tr>
                <th>Last Login</th>
                <th>{{data.last_login}}</th>
            </tr>

        </table>
    </div>
    </div>
{% endblock %}